[project]
name = "seed-farmer-docs-rewrite"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "mkdocs>=1.4.0",
    "mkdocs-material>=9.0.0",
    "mkdocs-minify-plugin>=0.6.0",
    "pymdown-extensions>=9.0",
    "diagrams>=0.23.0",
    "graphviz>=0.20.0"
]

